// <auto-generated />
using System;
using Folders.Data.ContextData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Folders.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231030180125_InitMigrations")]
    partial class InitMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Folders.Model.Catalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Catalogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f79deddb-43e2-47ec-9457-9327cde636e4"),
                            Name = "Creating Digital Images"
                        },
                        new
                        {
                            Id = new Guid("0cda4ae2-536a-429a-a8de-86099059dbb5"),
                            Name = "Resources",
                            ParentCatalogId = new Guid("f79deddb-43e2-47ec-9457-9327cde636e4")
                        },
                        new
                        {
                            Id = new Guid("9228ddfd-5399-4175-8374-eb34073a20b3"),
                            Name = "Evidence",
                            ParentCatalogId = new Guid("f79deddb-43e2-47ec-9457-9327cde636e4")
                        },
                        new
                        {
                            Id = new Guid("0194445f-828f-44e0-b042-084322ba396d"),
                            Name = "Grafic Products",
                            ParentCatalogId = new Guid("f79deddb-43e2-47ec-9457-9327cde636e4")
                        },
                        new
                        {
                            Id = new Guid("d27cf983-9ef0-479d-b670-d76267215b9c"),
                            Name = "Primary Source",
                            ParentCatalogId = new Guid("0cda4ae2-536a-429a-a8de-86099059dbb5")
                        },
                        new
                        {
                            Id = new Guid("7018b137-bf6b-424d-a8a9-a010618616e3"),
                            Name = "Secondary Source",
                            ParentCatalogId = new Guid("0cda4ae2-536a-429a-a8de-86099059dbb5")
                        },
                        new
                        {
                            Id = new Guid("319b2571-12f2-44b5-a958-4966ccfa1c87"),
                            Name = "Process",
                            ParentCatalogId = new Guid("0194445f-828f-44e0-b042-084322ba396d")
                        },
                        new
                        {
                            Id = new Guid("f9003b53-9ff6-441b-8f4a-9302b062911c"),
                            Name = "Final Product",
                            ParentCatalogId = new Guid("0194445f-828f-44e0-b042-084322ba396d")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
